language: python
cache: pip
python:
  - '3.7'

env:
  global:
    - ORG="python-sprints"
    - EMAIL="joytolia@hotmail.com"
    - REPO="pyntxos-dashboard"
    - COPY_DIR_FILE="./data ./utils environment.yml requirements.txt dashboard.ipynb"
    - GH_REPO="git@github.com:${ORG}/${REPO}.git"

before_install:
  - openssl aes-256-cbc -K $encrypted_bcb8af953825_key -iv $encrypted_bcb8af953825_iv -in github_deploy_key.enc -out github_deploy_key -d

install:
  - pip install -r scrape_requirements.txt

script:
  - python -c 'import utils.scrape; import utils.data; utils.data.dump(utils.scrape.scrape())'
  - git clone ${GH_REPO}
  - cd ${REPO}
  - rm -rf ${COPY_DIR_FILE}
  - cd ..
  - mv ${COPY_DIR_FILE} ${REPO}
  - cd ${REPO}
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add ${COPY_DIR_FILE}
  - git diff --quiet && git diff --staged --quiet || git commit -m "update data and dashboard"
  - git push "${GH_REPO}" master

